# Generated by Django 5.1.15 on 2026-04-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ремстрой', max_length=120, verbose_name='Название сайта')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Слоган (1 строка)')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email для заявок')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес офиса')),
                ('settlement_name', models.CharField(default='Красная смородина', max_length=120, verbose_name='Название посёлка')),
                ('settlement_location', models.CharField(default='д. Кисловка, Томская область', max_length=200, verbose_name='Расположение посёлка')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Юр. наименование')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('ogrnip', models.CharField(blank=True, max_length=20, verbose_name='ОГРНИП')),
                ('vk_url', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('yandex_map_iframe', models.TextField(blank=True, help_text='Вставьте полный <iframe> из Яндекс.Карт для блока Контакты', verbose_name='Iframe Яндекс.Карты')),
                ('yandex_metrika_id', models.CharField(blank=True, max_length=20, verbose_name='ID Яндекс.Метрики')),
                ('about_short', models.TextField(blank=True, verbose_name='О компании (короткий текст для футера)')),
                ('seo_title_default', models.CharField(blank=True, max_length=200, verbose_name='SEO Title по умолчанию')),
                ('seo_description_default', models.CharField(blank=True, max_length=300, verbose_name='SEO Description по умолчанию')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
