# Generated by Django 5.1.15 on 2026-04-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_escrow',
            field=models.TextField(blank=True, help_text='Параграф про эскроу-счета и банки-партнёры', verbose_name='О компании — про эскроу и банки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_intro',
            field=models.TextField(blank=True, help_text='Лид-абзац в начале страницы «О компании»', verbose_name='О компании — вступление'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_outro',
            field=models.TextField(blank=True, help_text='Финальный параграф (для кого подходит)', verbose_name='О компании — заключение'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_settlement',
            field=models.TextField(blank=True, help_text='Параграф про собственный посёлок «Красная Смородина»', verbose_name='О компании — про посёлок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='advantages_list',
            field=models.TextField(blank=True, verbose_name='Преимущества (по одному пункту в строке)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='directions_list',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки', verbose_name='Направления деятельности (по одному пункту в строке)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='partner_banks',
            field=models.CharField(blank=True, help_text='Через запятую: Сбербанк, Альфа-Банк, Левобережный, ДОМ.РФ', max_length=300, verbose_name='Банки-партнёры'),
        ),
    ]
