# Generated by Django 5.1.15 on 2026-04-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sitesettings_about_escrow_sitesettings_about_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_url',
            field=models.URLField(blank=True, help_text='Ссылка вида https://max.ru/u/USERNAME — российский мессенджер', verbose_name='MAX (мессенджер)'),
        ),
    ]
