# Generated by Django 5.1.15 on 2026-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sitesettings_max_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='office_map_iframe',
            field=models.TextField(blank=True, help_text='<iframe> для страницы Контакты, если офис не в посёлке', verbose_name='Iframe Яндекс.Карты — офис компании'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='settlement_plan',
            field=models.ImageField(blank=True, help_text='Изображение генплана с участками — отображается на странице посёлка', null=True, upload_to='site/', verbose_name='Генплан посёлка (картинка)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='yandex_map_iframe',
            field=models.TextField(blank=True, help_text='Вставьте полный <iframe> из Яндекс.Карт для страницы посёлка', verbose_name='Iframe Яндекс.Карты — посёлок Красная смородина'),
        ),
    ]
