# Generated by Django 5.1.15 on 2026-04-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_sitesettings_office_map_iframe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_verification',
            field=models.CharField(blank=True, help_text="Значение content из meta name='google-site-verification'", max_length=120, verbose_name='Google verification (для Search Console)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Например: "Пн-Пт 9:00-18:00, Сб 10:00-15:00"', max_length=120, verbose_name='Часы работы офиса'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_verification',
            field=models.CharField(blank=True, help_text="Значение content из meta name='yandex-verification' для подтверждения сайта в Яндекс.Вебмастере", max_length=120, verbose_name='Yandex verification (для Яндекс.Вебмастера)'),
        ),
    ]
