# Generated by Django 5.1.15 on 2026-04-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_sitesettings_google_verification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('home', 'Главная (/)'), ('builds', 'Каталог проектов (/builds)'), ('faq', 'Вопросы и ответы (/faq)'), ('about', 'О компании (/about)'), ('contacts', 'Контакты (/contacts)'), ('settlement', 'Посёлок (/settlement)')], help_text='Какую именно страницу сайта редактируем', max_length=20, unique=True, verbose_name='Страница')),
                ('kicker', models.CharField(blank=True, help_text='Маленькая надпись над h1, обычно одно-два слова, например: «Каталог», «FAQ», «О компании»', max_length=80, verbose_name='Мини-метка над заголовком')),
                ('title', models.CharField(blank=True, help_text='Большой заголовок, который видит посетитель в самом верху страницы. Если оставить пустым — будет показан стандартный текст из кода.', max_length=200, verbose_name='Заголовок страницы (h1)')),
                ('subtitle', models.TextField(blank=True, help_text='Короткий пояснительный текст под h1 (1–3 предложения). Не виден напрямую если оставить пустым.', verbose_name='Лид-абзац под заголовком')),
                ('meta_title', models.CharField(blank=True, help_text='Заголовок страницы во вкладке браузера и в выдаче поисковика. Если пусто — берётся title.', max_length=200, verbose_name='SEO Title (для Google/Яндекс)')),
                ('meta_description', models.CharField(blank=True, help_text='Описание страницы для поисковиков (до ~160 символов). Показывается в результатах поиска.', max_length=300, verbose_name='SEO Description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тексты страницы',
                'verbose_name_plural': 'Тексты страниц',
                'ordering': ['slug'],
            },
        ),
    ]
