# Generated by Django 5.1.15 on 2026-04-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_seed_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='founded_year',
            field=models.PositiveSmallIntegerField(default=2016, help_text='Используется в Hero на главной: «На рынке с 2016 года». Также вычисляется стаж компании.', verbose_name='Год основания / выхода на рынок'),
        ),
    ]
