# Generated by Django 5.1.15 on 2026-04-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_sitesettings_founded_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='office_map_iframe',
            field=models.TextField(blank=True, help_text='Код «iframe» из Яндекс.Карт для страницы Контакты, если офис не в посёлке.', verbose_name='Iframe Яндекс.Карты — офис компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='yandex_map_iframe',
            field=models.TextField(blank=True, help_text='Вставьте полный код «iframe» из Яндекс.Карт для страницы посёлка.', verbose_name='Iframe Яндекс.Карты — посёлок Красная смородина'),
        ),
    ]
