# Generated by Django 5.1.15 on 2026-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_fix_iframe_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homes_built_total',
            field=models.PositiveSmallIntegerField(default=30, help_text='Число в Hero на главной: «N построено». Учитываются все объекты, не только в посёлке. На сайте показывается со знаком «+» (например, «30+»).', verbose_name='Всего построено домов'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='settlement_homes_built',
            field=models.PositiveSmallIntegerField(default=12, help_text='Сколько домов в посёлке «Красная смородина» уже сданы. Используется в блоке статистики посёлка.', verbose_name='Построено домов в посёлке'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='settlement_homes_total',
            field=models.PositiveSmallIntegerField(default=40, help_text='Сколько всего домов запланировано в посёлке. На сайте будет показано «N из M уже построены».', verbose_name='Всего домов в посёлке (план)'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='slug',
            field=models.CharField(choices=[('home', 'Главная (/)'), ('builds', 'Каталог проектов (/builds)'), ('portfolio', 'Реализованные объекты (/portfolio)'), ('faq', 'Вопросы и ответы (/faq)'), ('about', 'О компании (/about)'), ('contacts', 'Контакты (/contacts)'), ('settlement', 'Посёлок (/settlement)')], help_text='Какую именно страницу сайта редактируем', max_length=20, unique=True, verbose_name='Страница'),
        ),
    ]
