# Generated by Django 5.1.15 on 2026-04-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_seed_portfolio_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='slug',
            field=models.CharField(choices=[('home', 'Главная (/)'), ('builds', 'Каталог проектов (/builds)'), ('portfolio', 'Реализованные объекты (/portfolio)'), ('faq', 'Вопросы и ответы (/faq)'), ('about', 'О компании (/about)'), ('contacts', 'Контакты (/contacts)'), ('settlement', 'ЖК (/settlement)')], help_text='Какую именно страницу сайта редактируем', max_length=20, unique=True, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_settlement',
            field=models.TextField(blank=True, help_text='Параграф про собственный ЖК «Красная смородина»', verbose_name='О компании — про ЖК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homes_built_total',
            field=models.PositiveSmallIntegerField(default=30, help_text='Число в Hero на главной: «N построено». Учитываются все объекты, не только в ЖК. На сайте показывается со знаком «+» (например, «30+»).', verbose_name='Всего построено домов'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='office_map_iframe',
            field=models.TextField(blank=True, help_text='Код «iframe» из Яндекс.Карт для страницы Контакты, если офис не в ЖК.', verbose_name='Iframe Яндекс.Карты — офис компании'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='settlement_homes_built',
            field=models.PositiveSmallIntegerField(default=12, help_text='Сколько домов в ЖК «Красная смородина» уже сданы. Используется в блоке статистики ЖК.', verbose_name='Построено домов в ЖК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='settlement_homes_total',
            field=models.PositiveSmallIntegerField(default=40, help_text='Сколько всего домов запланировано в ЖК. На сайте будет показано «N из M уже построены».', verbose_name='Всего домов в ЖК (план)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='settlement_location',
            field=models.CharField(default='д. Кисловка, Томская область', max_length=200, verbose_name='Расположение ЖК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='settlement_name',
            field=models.CharField(default='Красная смородина', max_length=120, verbose_name='Название ЖК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='settlement_plan',
            field=models.ImageField(blank=True, help_text='Изображение генплана с участками — отображается на странице ЖК', null=True, upload_to='site/', verbose_name='Генплан ЖК (картинка)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='yandex_map_iframe',
            field=models.TextField(blank=True, help_text='Вставьте полный код «iframe» из Яндекс.Карт для страницы ЖК.', verbose_name='Iframe Яндекс.Карты — ЖК «Красная смородина»'),
        ),
    ]
