# Generated by Django 5.1.15 on 2026-04-30 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Например: «Дом 180 м² в Кисловке». Если оставить пустым — на сайте будет показано краткое описание (площадь, год).', max_length=160, verbose_name='Название (опционально)')),
                ('description', models.TextField(blank=True, help_text='Что построили, особенности проекта, отзыв заказчика. Можно оставить пустым.', verbose_name='Краткое описание (опционально)')),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Например, 2024.', null=True, verbose_name='Год сдачи (опционально)')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Площадь, м² (опционально)')),
                ('location', models.CharField(blank=True, help_text='Например: «посёлок Красная смородина» или «д. Лоскутово».', max_length=200, verbose_name='Расположение (опционально)')),
                ('cover', models.ImageField(help_text='Главное фото, которое показывается в карточке на сайте. Большие фото автоматически сжимаются до 1920px.', upload_to='portfolio/', verbose_name='Обложка (главное фото)')),
                ('video_url', models.URLField(blank=True, help_text='Скопируй ссылку на видео из YouTube, RuTube, VK Видео или ВКонтакте — на сайте автоматически встроится плеер. Если ссылка с другого сервиса — будет ссылка «Смотреть видео».', verbose_name='Ссылка на видео (опционально)')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Меньшее число — выше в списке. Можно оставить 0.', verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, help_text='Сними галку, чтобы временно скрыть объект с сайта.', verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Реализованный объект',
                'verbose_name_plural': 'Реализованные объекты',
                'ordering': ('order', '-year', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolioitem', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Фото объекта',
                'verbose_name_plural': 'Фотографии объекта',
                'ordering': ('order', 'id'),
            },
        ),
    ]
