# Generated by Django 5.1.15 on 2026-04-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='location',
            field=models.CharField(blank=True, help_text='Например: «ЖК Красная смородина» или «д. Лоскутово».', max_length=200, verbose_name='Расположение (опционально)'),
        ),
    ]
