# Generated by Django 5.1.15 on 2026-08-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0010_seed_estimates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название акции')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Слаг (URL)')),
                ('badge_label', models.CharField(default='Акция', max_length=40, verbose_name='Текст значка на карточке дома')),
                ('banner_title', models.CharField(blank=True, help_text='Если пусто — используется название акции', max_length=200, verbose_name='Заголовок баннера')),
                ('banner_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок баннера')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Картинка баннера')),
                ('terms', models.TextField(help_text='Например: «Скидка действует при заключении договора строительного подряда до 31.12.2026»', verbose_name='Условия акции')),
                ('contract_deadline', models.DateField(blank=True, help_text='Крайний срок подписания договора для получения акционной цены', null=True, verbose_name='Заключить договор до')),
                ('starts_at', models.DateField(verbose_name='Акция действует с')),
                ('ends_at', models.DateField(verbose_name='Акция действует по')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['ends_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Акционная цена, ₽')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_links', to='builds.build', verbose_name='Дом')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_links', to='promotions.promotion', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Дом по акции',
                'verbose_name_plural': 'Дома по акции',
                'ordering': ['id'],
                'unique_together': {('promotion', 'build')},
            },
        ),
    ]
