# Generated by Django 5.1.15 on 2026-03-02 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Слаг (URL)')),
                ('area', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Площадь, м²')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена, ₽')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Дом под ключ',
                'verbose_name_plural': 'Дома под ключ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='builds/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='builds.build', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Фото дома',
                'verbose_name_plural': 'Фото домов',
                'ordering': ['order', 'id'],
            },
        ),
    ]
