# Generated by Django 5.1.15 on 2026-03-02 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='specs_layout',
            field=models.JSONField(blank=True, default=dict, verbose_name='Объемно-планировочные решения'),
        ),
        migrations.AddField(
            model_name='build',
            name='specs_main',
            field=models.JSONField(blank=True, default=dict, verbose_name='Основные характеристики'),
        ),
        migrations.AddField(
            model_name='build',
            name='specs_networks',
            field=models.JSONField(blank=True, default=dict, verbose_name='Подключение к сетям'),
        ),
        migrations.AddField(
            model_name='build',
            name='specs_struct',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конструктивные решения'),
        ),
        migrations.CreateModel(
            name='BuildEstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_title', models.CharField(max_length=220, verbose_name='Название этапа')),
                ('materials_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость материалов, ₽')),
                ('works_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость работ, ₽')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_items', to='builds.build', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Строка сметы',
                'verbose_name_plural': 'Смета',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BuildFacadeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='builds/facades/', verbose_name='Схема фасадов')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facades', to='builds.build', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Схема фасада',
                'verbose_name_plural': 'Схемы фасадов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BuildFloorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='builds/floors/', verbose_name='Поэтажный план')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='builds.build', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Поэтажный план',
                'verbose_name_plural': 'Поэтажные планы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BuildPlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='builds/plans/', verbose_name='Планировка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='builds.build', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
                'ordering': ['order', 'id'],
            },
        ),
    ]
