# Generated by Django 5.1.15 on 2026-03-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_build_specs_layout_build_specs_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildplanimage',
            name='build',
        ),
        migrations.AlterModelOptions(
            name='buildfacadeimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Схема фасадов', 'verbose_name_plural': 'Схемы фасадов'},
        ),
        migrations.RemoveField(
            model_name='build',
            name='specs_layout',
        ),
        migrations.RemoveField(
            model_name='build',
            name='specs_main',
        ),
        migrations.RemoveField(
            model_name='build',
            name='specs_networks',
        ),
        migrations.RemoveField(
            model_name='build',
            name='specs_struct',
        ),
        migrations.AlterField(
            model_name='buildimage',
            name='image',
            field=models.ImageField(upload_to='builds/', verbose_name='Фото дома'),
        ),
        migrations.CreateModel(
            name='EstimateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название этапа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Этап сметы',
                'verbose_name_plural': 'Этапы сметы',
                'ordering': ['order', 'id'],
                'unique_together': {('title',)},
            },
        ),
        migrations.CreateModel(
            name='BuildEstimateValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость материалов, ₽')),
                ('works_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость работ, ₽')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_values', to='builds.build', verbose_name='Дом')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='builds.estimatestage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Строка сметы',
                'verbose_name_plural': 'Смета',
                'ordering': ['stage__order', 'id'],
                'unique_together': {('build', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='SpecKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('main', 'Основные характеристики'), ('networks', 'Подключение к сетям'), ('layout', 'Объемно-планировочные решения'), ('struct', 'Конструктивные решения')], max_length=20, verbose_name='Раздел')),
                ('title', models.CharField(max_length=220, verbose_name='Название поля')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Поле характеристик',
                'verbose_name_plural': 'Поля характеристик',
                'ordering': ['section', 'order', 'id'],
                'unique_together': {('section', 'title')},
            },
        ),
        migrations.CreateModel(
            name='BuildSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500, verbose_name='Значение')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='builds.build', verbose_name='Дом')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='builds.speckey', verbose_name='Поле')),
            ],
            options={
                'verbose_name': 'Характеристика дома',
                'verbose_name_plural': 'Характеристики дома',
                'ordering': ['key__section', 'key__order', 'id'],
                'unique_together': {('build', 'key')},
            },
        ),
        migrations.DeleteModel(
            name='BuildEstimateItem',
        ),
        migrations.DeleteModel(
            name='BuildPlanImage',
        ),
    ]
