# Generated by Django 5.1.15 on 2026-04-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_remove_buildplanimage_build_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Проект дома', 'verbose_name_plural': 'Проекты домов'},
        ),
        migrations.AddField(
            model_name='build',
            name='available_in_settlement',
            field=models.BooleanField(default=True, verbose_name='Можно построить в посёлке Красная смородина'),
        ),
        migrations.AddField(
            model_name='build',
            name='available_on_client_land',
            field=models.BooleanField(default=True, verbose_name='Можно построить на участке клиента'),
        ),
        migrations.AddField(
            model_name='build',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Спален'),
        ),
        migrations.AddField(
            model_name='build',
            name='floors',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Этажность'),
        ),
        migrations.AddField(
            model_name='build',
            name='is_typical',
            field=models.BooleanField(default=True, verbose_name='Типовой проект'),
        ),
        migrations.AddField(
            model_name='build',
            name='plot_number',
            field=models.CharField(blank=True, help_text='Если проект привязан к конкретному участку поселка', max_length=20, verbose_name='Номер участка на генплане'),
        ),
        migrations.AddField(
            model_name='build',
            name='status',
            field=models.CharField(choices=[('planned', 'Проект (свободный участок)'), ('building', 'Строится'), ('available', 'Готов, продаётся'), ('sold', 'Продан')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='build',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена от, ₽'),
        ),
        migrations.AlterField(
            model_name='buildfloorimage',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors_images', to='builds.build', verbose_name='Дом'),
        ),
    ]
