# Generated by Django 5.1.15 on 2026-04-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_alter_build_options_build_available_in_settlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speckey',
            name='default_value',
            field=models.CharField(blank=True, help_text='Подставится при создании нового проекта дома; затем редактируется на карточке', max_length=500, verbose_name='Значение по умолчанию'),
        ),
    ]
