# Generated by Django 5.1.15 on 2026-04-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_speckey_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='available_in_settlement',
            field=models.BooleanField(default=True, verbose_name='Можно построить в ЖК «Красная смородина»'),
        ),
        migrations.AlterField(
            model_name='build',
            name='plot_number',
            field=models.CharField(blank=True, help_text='Если проект привязан к конкретному участку ЖК', max_length=20, verbose_name='Номер участка на генплане'),
        ),
    ]
