# Generated by Django 5.1.15 on 2026-04-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0004_alter_build_options_build_available_in_settlement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('source', models.CharField(choices=[('homepage', 'Главная'), ('project', 'Карточка проекта'), ('contacts', 'Страница контактов'), ('catalog', 'Каталог'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Источник')),
                ('page_url', models.URLField(blank=True, verbose_name='URL страницы')),
                ('utm_source', models.CharField(blank=True, max_length=120, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=120, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=120, verbose_name='utm_campaign')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Закрыта'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='builds.build', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
