# Generated by Django 5.1.15 on 2026-09-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('homepage', 'Главная'), ('project', 'Карточка проекта'), ('contacts', 'Страница контактов'), ('catalog', 'Каталог'), ('mortgage', 'Калькулятор ипотеки'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Источник'),
        ),
    ]
